import os

from django.conf import settings
import pytest

from tests.utils import COMPRESS_ROOT


def pytest_configure():
    settings.configure(
        DEBUG=True,
        SECRET_KEY='*****',
        INSTALLED_APPS=(
            'django.contrib.staticfiles',
            'compressor',
            'compressor_toolkit',
            'tests.test_project.base',
            'tests.test_project.app'
        ),
        ROOT_URLCONF='tests.test_project.urls',
        STATIC_URL='/static/',
        STATICFILES_FINDERS=(
            'django.contrib.staticfiles.finders.FileSystemFinder',
            'django.contrib.staticfiles.finders.AppDirectoriesFinder',
            'compressor.finders.CompressorFinder'
        ),
        MIDDLEWARE_CLASSES=(),
        TEMPLATE_CONTEXT_PROCESSORS=(
            'django.template.context_processors.static',
        ),
        COMPRESS_ROOT=COMPRESS_ROOT,
        COMPRESS_PRECOMPILERS=(
            ('text/x-scss', 'compressor_toolkit.precompilers.SCSSFilter'),
            ('module', 'compressor_toolkit.precompilers.ES6Filter')
        ),
        COMPRESS_ENABLED=False
    )


@pytest.fixture
def assert_precompiled():
    """
    Fixture that does the following steps:

    - searches given static file, e.g. 'app/layout.scss'
    - finds corresponding pre-compiled file generated by ``django-compressor``
    - asserts pre-compiled file contents with given expected contents

    Usage:

        assert_precompiled('app/layout.scss', 'css', '.title {\n  font-size: 30px;\n}\n')
    """
    # can't import ``Compressor`` before Django is configured
    from compressor.base import Compressor

    def runner(original_file_path, file_type, compiled_file_contents):
        """
        :param original_file_path: e.g. 'app/layout.scss'
        :param file_type: 'css' or 'js'
        :param compiled_file_contents: e.g. '.title {\n  font-size: 30px;\n}\n'
        """
        original_file_name = os.path.basename(original_file_path)

        compiled_file_path = os.path.join(
            COMPRESS_ROOT,
            Compressor(output_prefix=file_type).get_filepath(
                compiled_file_contents,
                original_file_name
            )
        )

        assert os.path.exists(compiled_file_path), \
            "Compiled file \"{}\" not found".format(compiled_file_path)

        with open(compiled_file_path) as compiled_file:
            assert compiled_file.read() == compiled_file_contents

    return runner


